### ISSUE TITLE
Trying to play RTSP via remote VLC doesn't work and will occasionally crash the server

### ISSUE THREAD

**Issue by fozzle** [tan-tan-kanarek/mediasoup-server#17]
Hey, me again :) Kind of a combo bug-report slash question here.

I've been messing around trying to get the RTSP stream from a cloud server to play on my local machine's VLC. I'm using the demo app that you provided. I see the RTSP requests show up in logs but VLC reports that it cannot understand the codecs. VLC seems to attempt to retry a few times, and sometimes will crash the server yielding this stack trace:

```
/home/kyle/mediasoup-server/node_modules/rtsp-stream/lib/request-line.js:13
  if (!match) throw new Error('Invalid RTSP Request-Line: ' + util.inspect(line))
              ^

Error: Invalid RTSP Request-Line: '$\u0001\u0000\u0010��\u0000\u0001΅�ց�\u0000\u0001΅��$\u0003\u0000\u0010��\u0000\u0001\u001e��|��\u0000\u0001\u001e��|\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000'
    at Object.exports.parse (/home/kyle/mediasoup-server/node_modules/rtsp-stream/lib/request-line.js:13:21)
    at new module.exports (/home/kyle/mediasoup-server/node_modules/rtsp-stream/lib/incoming-message.js:26:24)
    at module.exports.Decoder._writeHead (/home/kyle/mediasoup-server/node_modules/rtsp-stream/decoder.js:54:15)
    at module.exports.Decoder._writeOffset (/home/kyle/mediasoup-server/node_modules/rtsp-stream/decoder.js:37:21)
    at module.exports.Decoder._write (/home/kyle/mediasoup-server/node_modules/rtsp-stream/decoder.js:27:8)
    at doWrite (/home/kyle/mediasoup-server/node_modules/rtsp-stream/node_modules/readable-stream/lib/_stream_writable.js:401:64)
    at writeOrBuffer (/home/kyle/mediasoup-server/node_modules/rtsp-stream/node_modules/readable-stream/lib/_stream_writable.js:390:5)
    at module.exports.Writable.write (/home/kyle/mediasoup-server/node_modules/rtsp-stream/node_modules/readable-stream/lib/_stream_writable.js:317:11)
    at Socket.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:588:20)
```

I'll look into finding where this error can be caught so that the server doesn't get torn down.

In any case, the RTSP stream seems to work for the server-located ffmpeg recorder. Just VLC doesn't. And I'm trying to understand why because I was hoping to use the RTSP server to stream directly to another legacy media server (removing the intermediary FFMPEG step).

Have you had any success getting VLC to play RTSP from this server or is that just not possible with VLC?

EDIT: I notice that in FFMPEG it can often take a long time to properly detect the incoming stream. I presume this is why the probe size and analyze duration are set to the max value. I wonder if perhaps my problem in VLC playback is just related to a shorter default probe size and analyze duration? If that was the case, I'm curious if there's any methods to reduce the amount of time this takes.

**Comment by tan-tan-kanarek** [comment]
Thanks for the bug reports.
Could you please run the VLC with debug logs switched on?

**Comment by fozzle** [comment]
Does this help?

```
\f0\fs24 \cf2 core debug: VLC media player - 2.2.4 Weatherwax\
core debug: Copyright \'ac\'a9 1996-2016 the VideoLAN team\
core debug: revision 2.2.4-3-g2fc51dd\
core debug: configured with ../extras/package/macosx/../../../configure  '--prefix=/Users/fpk/Desktop/vlc-2.2/release/vlc_install_dir' '--enable-macosx' '--enable-merge-ffmpeg' '--enable-growl' '--enable-faad' '--enable-flac' '--enable-theora' '--enable-shout' '--enable-ncurses' '--enable-twolame' '--enable-realrtsp' '--enable-libass' '--enable-macosx-eyetv' '--enable-macosx-qtkit' '--enable-macosx-avfoundation' '--disable-skins2' '--disable-xcb' '--disable-caca' '--disable-sdl' '--disable-samplerate' '--disable-macosx-dialog-provider' '--with-macosx-version-min=10.6' '--build=x86_64-apple-darwin10' 'build_alias=x86_64-apple-darwin10' 'CC=xcrun clang' 'CFLAGS=' 'LDFLAGS=' 'CXX=xcrun clang++' 'OBJC=xcrun clang'\
macosx debug: Found 1 video capture devices\
macosx debug: Found 1 audio capture devices\
core debug: adding item `rtsp://35.185.46.44:5000/10040362.sdp' ( rtsp://35.185.46.44:5000/10040362.sdp )\
core debug: meta ok for (null), need to fetch art\
core debug: processing request item: rtsp://35.185.46.44:5000/10040362.sdp, node: Playlist, skip: 0\
core debug: rebuilding array of current - root Playlist\
core debug: rebuild done - 1 items, index 0\
core debug: starting playback of the new playlist item\
core debug: resyncing on rtsp://35.185.46.44:5000/10040362.sdp\
core debug: rtsp://35.185.46.44:5000/10040362.sdp is at 0\
core debug: creating new input thread\
core debug: Creating an input for 'rtsp://35.185.46.44:5000/10040362.sdp'\
core debug: looking for meta fetcher module matching "any": 1 candidates\
lua debug: Trying Lua scripts in /Users/kylepetrovich/Library/Application Support/org.videolan.vlc/lua/meta/fetcher\
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/lua/meta/fetcher\
core debug: requesting art for rtsp://35.185.46.44:5000/10040362.sdp\
core debug: using timeshift granularity of 50 MiB, in path '/tmp'\
core debug: `rtsp://35.185.46.44:5000/10040362.sdp' gives access `rtsp' demux `' path `35.185.46.44:5000/10040362.sdp'\
core debug: specified demux `any'\
core debug: looking for meta fetcher module matching "any": 1 candidates\
core debug: creating demux: access='rtsp' demux='any' location='35.185.46.44:5000/10040362.sdp' file='(null)'\
lua debug: Trying Lua scripts in /Users/kylepetrovich/Library/Application Support/org.videolan.vlc/lua/meta/fetcher\
core debug: looking for access_demux module matching "rtsp": 14 candidates\
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/lua/meta/fetcher\
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/fetcher/tvrage.luac\
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/fetcher/tvrage.luac\
lua debug: skipping script (unmatched scope) /Applications/VLC.app/Contents/MacOS/share/lua/meta/fetcher/tvrage.luac\
lua debug: skipping script (unmatched scope) /Applications/VLC.app/Contents/MacOS/share/lua/meta/fetcher/tvrage.luac\
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/share/lua/meta/fetcher\
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/share/lua/meta/fetcher\
core debug: no meta fetcher modules matched\
core debug: no meta fetcher modules matched\
core debug: searching art for rtsp://35.185.46.44:5000/10040362.sdp\
core debug: searching art for rtsp://35.185.46.44:5000/10040362.sdp\
core debug: looking for art finder module matching "any": 2 candidates\
core debug: looking for art finder module matching "any": 2 candidates\
lua debug: Trying Lua scripts in /Users/kylepetrovich/Library/Application Support/org.videolan.vlc/lua/meta/art\
lua debug: Trying Lua scripts in /Users/kylepetrovich/Library/Application Support/org.videolan.vlc/lua/meta/art\
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/lua/meta/art\
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/lua/meta/art\
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/00_musicbrainz.luac\
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/00_musicbrainz.luac\
lua debug: skipping script (unmatched scope) /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/00_musicbrainz.luac\
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/01_googleimage.luac\
live555 debug: version 2016.02.22\
lua debug: skipping script (unmatched scope) /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/00_musicbrainz.luac\
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/01_googleimage.luac\
lua debug: skipping script (unmatched scope) /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/01_googleimage.luac\
lua debug: skipping script (unmatched scope) /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/01_googleimage.luac\
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/02_frenchtv.luac\
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/02_frenchtv.luac\
lua debug: skipping script (unmatched scope) /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/02_frenchtv.luac\
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/03_lastfm.luac\
lua debug: skipping script (unmatched scope) /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/02_frenchtv.luac\
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/03_lastfm.luac\
lua debug: skipping script (unmatched scope) /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/03_lastfm.luac\
lua debug: skipping script (unmatched scope) /Applications/VLC.app/Contents/MacOS/share/lua/meta/art/03_lastfm.luac\
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/share/lua/meta/art\
core debug: no art finder modules matched\
core debug: art not found for rtsp://35.185.46.44:5000/10040362.sdp\
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/share/lua/meta/art\
core debug: no art finder modules matched\
core debug: art not found for rtsp://35.185.46.44:5000/10040362.sdp\
live555 debug: RTP subsession 'audio/OPUS'\
macosx debug: Enable media key support\
core debug: selecting program id=0\
live555 debug: RTP subsession 'video/H264'\
macosx warning: \cf3 variable stereo-mode doesn't exist or isn't handled\
\cf2 live555 debug: setup start: 0.000000 stop:0.000000\
macosx warning: \cf3 variable stereo-mode doesn't exist or isn't handled\
\cf2 live555 debug: play start: 0.000000 stop:0.000000\
core debug: using access_demux module "live555"\
core debug: looking for decoder module matching "any": 40 candidates\
core debug: no decoder modules matched\
core error: \cf4 could not identify codec\
\cf2 core debug: killing decoder fourcc `undf', 0 PES in FIFO\
core debug: looking for decoder module matching "any": 40 candidates\
avcodec debug: CPU flags: 0x0107d3db\
avcodec debug: trying to use direct rendering\
avcodec debug: allowing 4 thread(s) for decoding\
avcodec debug: avcodec codec (H264 - MPEG-4 AVC (part 10)) started\
avcodec debug: using frame thread mode with 4 threads\
core debug: using decoder module "avcodec"\
core debug: looking for packetizer module matching "any": 23 candidates\
core debug: using packetizer module "packetizer_h264"\
core debug: looking for meta reader module matching "any": 2 candidates\
lua debug: Trying Lua scripts in /Users/kylepetrovich/Library/Application Support/org.videolan.vlc/lua/meta/reader\
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/lua/meta/reader\
lua debug: Trying Lua playlist script /Applications/VLC.app/Contents/MacOS/share/lua/meta/reader/filename.luac\
lua debug: Trying Lua scripts in /Applications/VLC.app/Contents/MacOS/share/share/lua/meta/reader\
core debug: no meta reader modules matched\
core debug: `rtsp://35.185.46.44:5000/10040362.sdp' successfully opened\
macosx warning: \cf3 variable stereo-mode doesn't exist or isn't handled\
\cf2 macosx debug: prevented sleep through IOKit (33539)\
live555 warning: \cf3 no data received in 10s. Switching to TCP\
\cf2 core debug: removing module "avcodec"\
avcodec debug: ffmpeg codec (H264 - MPEG-4 AVC (part 10)) stopped\
core debug: killing decoder fourcc `h264', 0 PES in FIFO\
core debug: removing module "packetizer_h264"\
core debug: Program doesn't contain anymore ES\
live555 debug: RTP subsession 'audio/OPUS'\
core debug: looking for decoder module matching "any": 40 candidates\
core debug: no decoder modules matched\
core error: \cf4 could not identify codec\
\cf2 core debug: killing decoder fourcc `undf', 0 PES in FIFO\
live555 debug: RTP subsession 'video/H264'\
macosx warning: \cf3 variable stereo-mode doesn't exist or isn't handled\
\cf2 core debug: looking for decoder module matching "any": 40 candidates\
avcodec debug: CPU flags: 0x0107d3db\
avcodec debug: trying to use direct rendering\
avcodec debug: allowing 4 thread(s) for decoding\
avcodec debug: avcodec codec (H264 - MPEG-4 AVC (part 10)) started\
avcodec debug: using frame thread mode with 4 threads\
core debug: using decoder module "avcodec"\
core debug: looking for packetizer module matching "any": 23 candidates\
core debug: using packetizer module "packetizer_h264"\
live555 debug: setup start: 0.000000 stop:0.000000\
macosx warning: \cf3 variable stereo-mode doesn't exist or isn't handled\
\cf2 live555 error: \cf4 RTSP PLAY failed 500 Internal Server Error\
\cf2 live555 error: \cf4 TCP rollover failed, aborting\
\cf2 core debug: EOF reached\
core debug: finished input\
core debug: removing module "avcodec"\
avcodec debug: ffmpeg codec (H264 - MPEG-4 AVC (part 10)) stopped\
core debug: killing decoder fourcc `h264', 1 PES in FIFO\
core debug: removing module "packetizer_h264"\
core debug: removing module "live555"\
core debug: Program doesn't contain anymore ES\
core debug: dead input\
macosx debug: releasing sleep blocker (33539)\
core debug: changing item without a request (current 0/1)\
core debug: nothing to play\
```

**Comment by tan-tan-kanarek** [comment]
Can I understand that you used MAC? I think that MAC has license issue with h.264, anyway, it worked for me from VLC on Windows and cvlc on CentOS.

**Comment by fozzle** [comment]
I do have a mac. Perhaps that is the issue. Feel free to close, though the issue with the server crashing from invalid  RTSP requests is still at large.

**Comment by tan-tan-kanarek** [comment]
Regarding the error, it is asynchronously raised from rtsp-stream module.
