### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by jonahzheng** [tan-tan-kanarek/mediasoup-server#18]
1.run  node example.js
2.error info

/home/test/mediasoup-server/lib/rtsp/server.js:12
class RtspServer extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/test/mediasoup-server/index.js:7:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/test/mediasoup-server/example.js:9:22)
    at Module._compile (module.js:409:26)

**Comment by tan-tan-kanarek** [comment]
Please use node.js 6 or above.
